package com.helixdesk.enums;

public enum NotificationType {
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_REASSIGNED,
    TICKET_ESCALATED,
    SPECIALIST_RESPONSE,
    RESOLUTION_SUBMITTED,
    TICKET_REOPENED,
    TICKET_CLOSED,
    SLA_WARNING,
    SLA_BREACHED,
    INFORMATION_REQUESTED,
    AI_RESPONSE
}
