spring.application.name=helixdesk-api
spring.profiles.active=dev

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/helixdesk
spring.datasource.username=your username
spring.datasource.password=your password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.pool-name=helixdesk-pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

helixdesk.cors.allowed-origins=http://localhost:4200
helixdesk.jwt.secret=HelixDeskDevSecretKeyMustBeAtLeastThirtyTwoCharsLong!!
helixdesk.jwt.expiration-ms=86400000
helixdesk.uploads.dir=./uploads
helixdesk.ai.max-attempts=2
helixdesk.ai.llm-base-url=
helixdesk.ai.llm-api-key=
helixdesk.ai.llm-model=deepseek-chat

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true

info.app.name=HelixDesk
info.app.description=AI IT Help Desk / AI Ticket Resolution System
info.app.version=0.1.0-SNAPSHOT
info.app.phase=16

springdoc.api-docs.path=/api/docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
